---

- include_tasks: packages.yml
- include_tasks: jetbrains.yml
- include_tasks: rambox.yml
- include_tasks: slack.yml
- include_tasks: calendar.yml
- include_tasks: spotifyctl.yml
- include_tasks: flatpaks.yml
- include_tasks: snaps.yml
