---

- name: Install available RPMs
  become: true
  yum:
    state: present
    name:
      - vivaldi
      - spotify
      - sublime-text
      - fuse
      - docker-ce
      - openvpn
      - evolution
      - evolution-ews
      - gnome-screenshot
      - kpcli

- name: Add user to Docker group
  become: true
  user:
    name: "{{ user }}"
    append: true
    groups:
      - docker
