---

- name: Install pip packages
  become: true
  pip:
    executable: /usr/local/bin/pip3
    name:
      - requests_oauthlib
      - flask
      - wtforms
    state: present

- name: Copy Spotifyctl
  become: true
  copy:
    src: files/spotifyctl
    dest: /usr/local/bin/spotifyctl
    mode: 0755
