---

- name: Check if tmux is installed
  shell: which tmux
  changed_when: false
  ignore_errors: yes
  register: tmux

- block:
    - name: Install dependencies
      yum:
        name:
          - libevent-devel
          - ncurses-devel

    - name: Create tmp dir
      file:
        path: /tmp/tmux
        state: directory

    - name: Download tmux
      unarchive:
        remote_src: true
        src: "{{ tmux_url }}"
        dest: /tmp/tmux
        list_files: true
      register: tmux_dir

    - name: Install tmux
      become: true
      shell: |
        ./configure && make && make install
      args:
        chdir: "/tmp/tmux/{{ tmux_dir.files | last | dirname }}"

    - name: Cleanup
      become: true
      file:
        path: /tmp/tmux
        state: absent

  when: tmux.rc != 0 or update_tmux is defined

- name: Copy tmux config
  copy:
    src: files/tmux.conf
    dest: "/home/{{ user }}/.tmux.conf"

