---

- name: Check if tmux is installed
  shell: which tmux
  changed_when: false
  ignore_errors: yes
  register: tmux

- block:
    - name: Create tmp dir
      file:
        path: /tmp/tmux
        state: directory

    - name: Download tmux
      unarchive:
        remote_src: true
        src: "{{ tmux_url }}"
        dest: /tmp/tmux

    - name: Install tmux
      become: true
      shell: |
        ./configure && make && make install
      args:
        chdir: /tmp/tmux

    - name: Cleanup
      become: true
      file:
        path: /tmp/tmux
        state: absent

  when: tmux.rc != 0 or update_tmux is defined
