---

- name: Install dependencies and helpers
  become: true
  yum:
    state: present
    name:
      - pulseaudio
      - pulseaudio-utils
      - alsa-utils
      - alsa-tools
      - pavucontrol

- name: Configure Pulseaudio
  become: true
  copy:
    src: "audio/{{ item }}"
    dest: "/etc/pulse/{{ item }}"
  with_items:
    - default.pa
