---

- name: Install dependencies and helpers
  become: true
  yum:
    state: present
    name:
      - bluez
      - pulseaudio-module-bluetooth

- name: Configure Bluetooth
  become: true
  copy:
    src: bluetooth.conf
    dest: /etc/bluetooth/main.conf
