---

- name: install required display drivers
  become: true
  yum:
    name:
      - "mesa-dri-drivers"
      - "xorg-x11-drv-intel"
      - "arandr"
      - "acpid"
    state: present

- name: Copy fix script
  become: true
  copy:
    src: files/video/fix_video
    dest: /usr/lib/systemd/system-sleep/fix_video
    owner: root
    mode: 0755
