dbus-update-activation-environment --systemd DISPLAY
export $(dbus-launch)
eval $(ssh-agent)
export PATH="$PATH:$HOME/.zsh.d/bin"
xrandr --output eDP1 --dpi 125
xrdb ~/.Xresources
# FINALLY start i3
i3 > ~/.i3.log
