---

- name: Copy i3 config
  copy:
    src: files/i3_config
    dest: /home/{{ user }}/.config/i3/config

- name: Copy .i3 folder
  copy:
    src: files/i3/
    dest: /home/{{ user }}/.i3

- name: Copy XResources
  copy:
    src: files/xresources
    dest: "/home/{{ user }}/.Xresources"