---

- name: Check if dunst is installed
  stat:
    path: /usr/local/bin/dunst
  register: dunst

- block:
    - name: Install dependencies
      yum:
        name:
          - dbus-devel
          - glib-devel
          - libXinerama-devel
          - libXrandr-devel
          - libXScrnSaver-devel
          - cairo-devel
          - pango-devel
          - gtk3-devel

    - name: Clone Dunst repo
      git:
        repo: https://github.com/dunst-project/dunst.git
        depth: 1
        dest: /tmp/dunst

    - name: Install Dunst
      become: true
      shell: |
          make && make install
      args:
        chdir: /tmp/dunst

    - name: Cleanup
      file:
        path: /tmp/dunst
        state: absent

  when: not dunst.stat.exists

- name: Create dunst dir
  file:
    path: "/home/{{ user }}/.config/dunst"
    state: directory

- name: Copy Dunst config
  copy:
    src: files/dunstrc
    dest: "/home/{{ user }}/.config/dunst/dunstrc"

