---

- name: Install i3wm
  become: true
  package:
    name:
      - "i3"
      - "i3-lock"
      - "xterm"
    state: present

- name: Install py3status
  become: true
  pip:
    executable: /usr/local/bin/pip3
    name: py3status
