---

- name: Install i3wm
  become: true
  package:
    name:
      - "i3"
      - "mesa-dri-drivers"
      - "xorg-x11-server-Xorg"
      - "xorg-x11-xauth"
      - "xorg-x11-xinit"
      - "dbus-x11"
    state: present
