---

- name: Boot into graphical userinterface
  become: true
  shell: |
    systemctl set-default graphical.target

- name: Start i3 on X-Server start
  copy:
    src: files/xinitrc
    dest: /home/{{ user }}/.xinitrc
