#!/bin/bash
export DISPLAY="$(/usr/local/bin/getX)"
export XAUTHORITY="/home/$USER/.Xauthority"
echo -n "none" | sudo tee /sys/bus/serio/devices/serio1/drvctl
echo -n "reconnect" | sudo tee /sys/bus/serio/devices/serio1/drvctl
sleep 1
synclient HorizTwoFingerScroll=1
synclient TapButton1=1