#!/bin/bash
export DISPLAY=":0"
export XAUTHORITY="/home/$USER/.Xauthority"
logger $XAUTHORITY
echo -n "none" | sudo tee /sys/bus/serio/devices/serio1/drvctl
echo -n "reconnect" | sudo tee /sys/bus/serio/devices/serio1/drvctl
sleep 1
synclient HorizTwoFingerScroll=1
synclient TapButton1=1