export LANG=de_CH.UTF-8
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec startx; fi

# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' max-errors 1
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl true
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt autocd
bindkey -e

source ~/.zplug/init.zsh


zplug "arzzen/calc.plugin.zsh", use:calc.plugin.zsh
zplug "chrissicool/zsh-256color", use:zsh-256color.plugin.zsh
zplug "Cloudstek/zsh-plugin-appup", use:appup.plugin.zsh
zplug "desyncr/auto-ls", use:auto-ls.zsh
zplug "laggardkernel/thefuck", use:thefuck.plugin.zsh
zplug "sindresorhus/pretty-time-zsh", use:pretty-time.plugin.zsh
zplug "skx/sysadmin-util", use:sysadmin-util.plugin.zsh
zplug "soimort/translate-shell", use:translate-shell.plugin.zsh
zplug "sparsick/ansible-zsh", use:ansible.plugin.zsh
zplug "Tarrasch/zsh-bd", use:bd.plugin.zsh
zplug "valentinocossar/sublime", use:sublime.plugin.zsh
zplug "webyneter/docker-aliases", use:docker-aliases.plugin.zsh
zplug "zsh-users/zsh-autosuggestions", use:zsh-autosuggestions.plugin.zsh
zplug "zsh-users/zsh-history-substring-search", use:zsh-history-substring-search.plugin.zsh
zplug romkatv/powerlevel10k, use:powerlevel10k.zsh-theme
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
zplug load
for file in ~/.zsh.d/*.zsh; do
	source $file
done
