---

- name: install required display drivers
  become: true
  yum:
    name:
      - "xorg-x11-server-Xorg"
      - "xorg-x11-xauth"
      - "xorg-x11-xinit"
      - "xorg-x11-utils"
      - "dbus-x11"
      - "fwupd"
    state: present
