---

- name: Create local repo
  become: true
  file:
    path: /srv/yum-repo
    state: directory

- name: Install createrepo
  become: true
  yum:
    name: createrepo
    state: present

- name: Create local repo (for real)
  become: true
  shell: |
    createrepo /srv/yum-repo

- name: Copy repo files
  become: true
  copy:
    src: "{{item}}"
    dest: /etc/yum.repos.d
  with_fileglob: "files/*"
