---

- name: Install duplicity
  become: true
  yum:
    name: duplicity
    state: present

- name: Copy backup-script
  become: true
  copy:
    src: files/backup
    dest: "/usr/local/bin/backup"
    mode: 0755

- name: Enable cronjob
  cron:
    name: backup
    user: alex
    minute: 0
    hour: 13
    job: "/usr/local/bin/backup"
