#!/bin/bash

if ! mountpoint /backup; then
    sudo mount -a
fi > /dev/null

if ! mountpoint /backup > /dev/null; then
    echo "Cannot mount backup disk"
    exit 1
fi

LAST_FULL=$(duplicity collection-status file:///backup/home | tee | head -1 | cut -d":" -f2)
LAST_FULL_TIMESTAMP=$(date -d "${LAST_FULL}" +%s || echo "0")
CURRENT_TIMESTAMP=$(date +%s)
DIFF_FULL=$(($CURRENT_TIMESTAMP - $LAST_FULL_TIMESTAMP))
export PASSPHRASE=$(cat /etc/backup_passphrase)
if [[ ${DIFF_FULL} -gt 604800 ]]; then
    echo "Last full backup is older than 7 days, doing a new full"
    duplicity full /home file:///backup/home
else
    echo "Performing an incremental backup"
    duplicity incremental /home file:///backup/home
fi
