#!/bin/bash
if [[ -z $1 ]] | [[ "$1" == "post" ]]; then
    export DISPLAY="$(/usr/local/bin/getX)"
    export XAUTHORITY="/home/alex/.Xauthority"
    /usr/local/bin/monitorconfig_internal_only.sh >> /home/alex/log.txt 2>&1
    xset dpms force on >> /home/alex/log.txt 2>&1
fi