---

- name: Check if fonts are installed
  stat:
    path: "/home/{{ user }}/.local/share/fonts"
  register: fontpath


- block:
  - name: Create font folder
    file:
      path: "/home/{{ user }}/.local/share/fonts"
      state: directory

  - name: Download Nerd fonts FuraMono
    unarchive:
      remote_src: yes
      src: 'https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/FiraMono.zip'
      dest: /home/{{ user }}/.local/share/fonts/

  - name: Install fonts
    shell: fc-cache -f

  when: "not fontpath.stat.exists"
