---

- name: Check if fonts are installed
  stat:
    path: /home/{{ user }}/.local/share/fonts"
  register: fontpath


- block:
  - name: Clone Powerline fonts
    git:
      repo: 'https://github.com/powerline/fonts.git'
      dest: /tmp/fonts
      depth: 1

  - name: Install fonts
    shell: ./install.sh
    args:
      chdir: /tmp/fonts

  - name: Cleanup
    file:
      paht: /tmp/fonts
      state: absent

  when: "not fontpath.stat.exists"
