---

- include_tasks: snap.yml
- include_tasks: selinux.yml
- include_tasks: sysctl.yml

- name: Install os tools
  become: true
  package:
    name: "{{ packages }}"
    state: present

- name: Enable CUPS
  systemd:
    name: cups
    state: started
    enabled: true
