---

- include_tasks: snap.yml

- name: Install os tools
  become: true
  package:
    name: "{{ packages }}"
    state: present

#- name: Install Remmina
#  become: true
#  snap:
#    name: remmina
#    state: present
