---

- name: Check if zsh is installed
  shell: which zsh
  changed_when: false
  ignore_errors: yes
  register: zsh

- block:
    - name: Create tmp dir
      file:
        path: /tmp/zsh
        state: directory

    - name: Download zsh
      get_url:
        dest: /tmp/zsh.tar
        timeout: 60
        url: "{{ zsh_url }}"

    - name: Unpack zsh
      unarchive:
        src: /tmp/zsh.tar
        dest: /tmp/
        list_files: true
      register: zsh_dir

    - name: Install zsh
      become: true
      shell: |
        ./configure && make && make install
      args:
        chdir: "/tmp/{{ zsh_dir.files | last | regex_search('zsh[^/]*') }}"

    - name: Cleanup
      become: true
      file:
        path: /tmp/zsh
        state: absent
 
    - name: Install zplug
      shell: |
        curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh 

  when: zsh.rc != 0 or update_zsh is defined

- name: Copy zshrc
  copy:
    src: files/zshrc
    dest: "/home/{{ user }}/.zshrc"

- name: Create directory for additional configs
  file:
    path: "/home/{{ user }}/.zsh.d"
    state: directory

- name: Make zsh the default shell
  become: true
  user:
    name: "{{ user }}"
    shell: /usr/local/bin/zsh
